### PR TITLE
fix for issue #50

### PR DESCRIPTION
**Pull request by gurmeetb**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
lots of weird behaviors. See here: https://take.ms/4ecJa

**Comment by gurmeetb** [comment]
I saw the pointer jumping but looks like I missed click of same Menu item scenario. Checking what is going wrong there.

**Comment by gurmeetb** [comment]
@ThomasKranitsas Sorry looks like it is broken, if I try to sort this, it breaks for login. Can we open this for pickup so someone else can give a try?

**Comment by ThomasKranitsas** [comment]
Sure, I'll close this PR

**Pull request closed without merging**
